//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ru.shtrih_m.fr_drv_ng.classic_interface {

public class BytesVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<byte>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BytesVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BytesVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BytesVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          classic_fr_drv_ngPINVOKE.delete_BytesVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public BytesVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (byte element in c) {
      this.Add(element);
    }
  }

  public BytesVector(global::System.Collections.Generic.IEnumerable<byte> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (byte element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public byte this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(byte[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(byte[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, byte[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public byte[] ToArray() {
    byte[] array = new byte[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<byte> global::System.Collections.Generic.IEnumerable<byte>.GetEnumerator() {
    return new BytesVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new BytesVectorEnumerator(this);
  }

  public BytesVectorEnumerator GetEnumerator() {
    return new BytesVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class BytesVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<byte>
  {
    private BytesVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public BytesVectorEnumerator(BytesVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public byte Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (byte)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    classic_fr_drv_ngPINVOKE.BytesVector_Clear(swigCPtr);
  }

  public void Add(byte x) {
    classic_fr_drv_ngPINVOKE.BytesVector_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = classic_fr_drv_ngPINVOKE.BytesVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = classic_fr_drv_ngPINVOKE.BytesVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    classic_fr_drv_ngPINVOKE.BytesVector_reserve(swigCPtr, n);
  }

  public BytesVector() : this(classic_fr_drv_ngPINVOKE.new_BytesVector__SWIG_0(), true) {
  }

  public BytesVector(BytesVector other) : this(classic_fr_drv_ngPINVOKE.new_BytesVector__SWIG_1(BytesVector.getCPtr(other)), true) {
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  public BytesVector(int capacity) : this(classic_fr_drv_ngPINVOKE.new_BytesVector__SWIG_2(capacity), true) {
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  private byte getitemcopy(int index) {
    byte ret = classic_fr_drv_ngPINVOKE.BytesVector_getitemcopy(swigCPtr, index);
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private byte getitem(int index) {
    byte ret = classic_fr_drv_ngPINVOKE.BytesVector_getitem(swigCPtr, index);
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, byte val) {
    classic_fr_drv_ngPINVOKE.BytesVector_setitem(swigCPtr, index, val);
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(BytesVector values) {
    classic_fr_drv_ngPINVOKE.BytesVector_AddRange(swigCPtr, BytesVector.getCPtr(values));
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  public BytesVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = classic_fr_drv_ngPINVOKE.BytesVector_GetRange(swigCPtr, index, count);
    BytesVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new BytesVector(cPtr, true);
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, byte x) {
    classic_fr_drv_ngPINVOKE.BytesVector_Insert(swigCPtr, index, x);
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, BytesVector values) {
    classic_fr_drv_ngPINVOKE.BytesVector_InsertRange(swigCPtr, index, BytesVector.getCPtr(values));
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    classic_fr_drv_ngPINVOKE.BytesVector_RemoveAt(swigCPtr, index);
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    classic_fr_drv_ngPINVOKE.BytesVector_RemoveRange(swigCPtr, index, count);
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  public static BytesVector Repeat(byte value, int count) {
    global::System.IntPtr cPtr = classic_fr_drv_ngPINVOKE.BytesVector_Repeat(value, count);
    BytesVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new BytesVector(cPtr, true);
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    classic_fr_drv_ngPINVOKE.BytesVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    classic_fr_drv_ngPINVOKE.BytesVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, BytesVector values) {
    classic_fr_drv_ngPINVOKE.BytesVector_SetRange(swigCPtr, index, BytesVector.getCPtr(values));
    if (classic_fr_drv_ngPINVOKE.SWIGPendingException.Pending) throw classic_fr_drv_ngPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(byte value) {
    bool ret = classic_fr_drv_ngPINVOKE.BytesVector_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(byte value) {
    int ret = classic_fr_drv_ngPINVOKE.BytesVector_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(byte value) {
    int ret = classic_fr_drv_ngPINVOKE.BytesVector_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public bool Remove(byte value) {
    bool ret = classic_fr_drv_ngPINVOKE.BytesVector_Remove(swigCPtr, value);
    return ret;
  }

}

}
